// recipe-app/src/components/ui/main-layout/MainLayout.vue
<script setup lang="ts">
import { cn } from '@/lib/utils';
const props = withDefaults(defineProps<{ as?: keyof HTMLElementTagNameMap; class?: string }>(), {
  as: 'main',
});
</script>
<template>
  <component :is="props.as" :class="cn('container mt-16', props.class)">
    <slot />
  </component>
</template>

// react-recipe-app/src/components/MainLayout.tsx
import { HTMLAttributes, PropsWithChildren } from 'react';

import { cn } from '@/lib/utils';

type MainLayoutProps = {
  as?: keyof HTMLElementTagNameMap;
} & HTMLAttributes<unknown>;

export const MainLayout = ({
  as,
  children,
  className,
  ...rest
}: PropsWithChildren<MainLayoutProps>) => {
  const Component = as ? as : 'main';
  return (
    <Component {...rest} className={cn('container mt-16', className)}>
      {children}
    </Component>
  );
};
