// react-recipe-app/src/components/RecipeList.tsx
import { Link } from 'react-router-dom';

import { type Recipe } from '@/stores';

export const RecipeList = ({ recipes }: { recipes: Recipe[] }) => {
  return (
    <>
      {recipes.length ? (
        <nav>
          <ul className="p-0">
            {recipes.map((recipe) => {
              return (
                <li className="list-none" key={recipe.id}>
                  <Link to={`/recipe/${recipe.id}`}>{recipe.name}</Link>
                </li>
              );
            })}
          </ul>
        </nav>
      ) : (
        <div className="text-gray-500">No Recipes Found!</div>
      )}
    </>
  );
};

// recipe-app/src/components/RecipeList.vue
<script setup lang="ts">
import type { Recipe } from '@/stores';
import { RouterLink } from 'vue-router';
defineProps<{
  recipes: Recipe[];
}>();
</script>

<template>
  <nav v-if="!!recipes.length">
    <ul class="p-0">
      <li class="list-none" v-for="recipe in recipes" :key="recipe.id">
        <RouterLink class="prose max-w-none" :to="`/recipe/${recipe.id}`">
          {{ recipe.name }}
        </RouterLink>
      </li>
    </ul>
  </nav>
  <div v-else class="text-gray-500">No Recipes Found!</div>
</template>
