// recipe-app/src/views/RecipeView.vue
<script setup lang="ts">
import { MainLayout, Button } from '@/components';
import { useRecipeStore } from '@/stores';
import { computed } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
const store = useRecipeStore();

const route = useRoute();

const recipe = computed(() => {
  return store.getRecipeById(route.params.id as string);
});

const isFavorite = computed(() => {
  return store.isFavorite(route.params.id as string);
});
</script>

<template>
  <MainLayout>
    <h1>{{ recipe?.name }}</h1>
    <p>{{ recipe?.description }}</p>
    <div class="flex items-center gap-4">
      <Button variant="outline" class="not-prose" as-child>
        <RouterLink :to="{ name: 'editRecipe', params: { id: recipe?.id } }">Edit</RouterLink>
      </Button>
      <Button v-if="recipe" @click="store.toggleFavorite(recipe)">{{
        isFavorite ? 'Remove from Favorites' : 'Add to Favorites'
      }}</Button>
    </div>
  </MainLayout>
</template>

// react-recipe-app/src/views/RecipeView.tsx
import { Link, useParams } from 'react-router-dom';

import { Button, MainLayout } from '@/components';
import { useRecipeStore } from '@/stores';

export const RecipeView = () => {
  const { id } = useParams();
  const recipe = useRecipeStore((state) =>
    state.recipes.find((r) => r.id === id),
  );

  const toggleFavorite = useRecipeStore((state) => state.toggleFavorite);

  return (
    <MainLayout>
      <h1>{recipe?.name}</h1>
      <p>{recipe?.description}</p>
      <div className="flex items-center gap-4">
        <Button variant="outline" className="not-prose" asChild>
          <Link to={`/recipe-edit/${id}`}>Edit</Link>
        </Button>
        {recipe && (
          <Button
            onClick={() => {
              toggleFavorite(recipe);
            }}
          >
            {recipe?.favorite ? 'Remove from Favorites' : 'Add to Favorites'}
          </Button>
        )}
      </div>
    </MainLayout>
  );
};
