// react-recipe-app/src/views/FavoritesView.tsx
import { MainLayout, RecipeList } from '@/components';
import { useRecipeStore } from '@/stores';

export const FavoritesView = () => {
  const favorites = useRecipeStore((state) =>
    state.recipes.filter((r) => r.favorite),
  );
  return (
    <MainLayout>
      <h1>Favorite Recipes</h1>
      <RecipeList recipes={favorites} />
    </MainLayout>
  );
};

// recipe-app/src/views/FavoritesView.vue
<script setup lang="ts">
import { MainLayout, RecipeList } from '@/components';
import { useRecipeStore } from '@/stores';
const store = useRecipeStore();
</script>

<template>
  <MainLayout>
    <h1>Favorite Recipes</h1>
    <RecipeList :recipes="store.favoriteRecipes" />
  </MainLayout>
</template>
